# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: PyWorldWide Docs
site_url: https://docs.pyworldwide.org
site_description: "Documentation for PyWorldWide Volunteers on the meetup organization"
theme:
  name: material
  logo: assets/pyworldwide-logo.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  favicon: assets/favicon.ico
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.action.edit
  markdown_extensions:
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
nav:
  - Home: index.md
  - HOWTOs:
    - how to submit a talk: HOWTOs/how_to_submit_a_talk.md
  - Meetup:
    - meetup organize checklist: meetup/checklist_for_meetup_organization.md
  - Policies:
    - Terms of Service: policies/terms_of_use.md
    - Acceptable Use Policy: policies/acceptable_use_policy.md
    - Code of Conduct: https://policies.python.org/python.org/code-of-conduct/
repo_url: https://github.com/pyworldwide/docs
repo_name: pyworldwide/docs
edit_uri: edit/main/docs/
extra:
  homepage: https://docs.pyworldwide.org
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@pyworldwide
      name: Follow us on Mastodon
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/pyworldwide.bsky.social
      name: Follow us on BlueSky
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@pyworldwideorg
      name: Subscribe to our YouTube Channel
    - icon: material/hand-coin
      link: https://opencollective.com/pyworldwide
      name: Donate to PyWorldWide
    - icon: fontawesome/brands/github
      link: https://github.com/pyworldwide/docs
      name: Contribute to our repository
  social_card:
    size:
      width: 1200
      height: 630
    colors:
      primary: "#4051b5"
      accent: "#e91e63"
      background: "#4051b5ee"
      text: "#ffffff"
    layouts:
      - background:
          color: "#4051b5ee"
      - logo:
          image: assets/pyworldwide-logo.png
          position: "top left"
          width: 160
          height: 160
      - title:
          text: "PyWorldWide Volunteer Docs"
          color: "#ffffff"
          font: "Fira Sans"
          size: 64
          weight: 700
          wrap: true
      - subtitle:
          text: "Build, Contribute, Learn Together"
          color: "#ff80ab"
          font: "Fira Sans"
          size: 36
          weight: 400
      - author:
          text: "by PyWorldWide Community"
          color: "#d1c4e9"
          font: "Fira Mono"
          size: 24
          position: "bottom right"
plugins:
  - social
  - tags
  - rss
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: pyworldwide/docs
      branch: main